{% set name = "siscone" %}
{% set version = "3.0.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/fastjet/siscone/-/archive/siscone-{{ version }}/siscone-siscone-{{ version }}.tar.gz
  sha256: fd852e5ae3349a1ad540e49b1dd7efe3a188c3f7591902de4aeb781c421ddf13
  patches:
    - 0001-remove-os-libtoolize-assumptions.patch

build:
  skip: true  # [win]
  number: 1
  run_exports:
    - {{ pin_subpackage('siscone', max_pin='x.x') }}
  script:
    # Get an updated config.sub and config.guess
    - cp $BUILD_PREFIX/share/gnuconfig/config.* .
    - autoreconf --install
    - ./configure --help
    - bash autogen.sh --prefix=$PREFIX --disable-static
    - make --jobs="${CPU_COUNT}"
    - make check  # [build_platform == target_platform]
    - make install
    - make clean

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - automake
    - libtool
    - make
    - pkg-config
    - gnuconfig

test:
  source_files:
    - examples/main.cpp
    - examples/options.cpp
    - examples/options.h
    - examples/area.cpp
    - examples/sample.cpp
    - examples/test.cpp
    - examples/times.cpp
    - examples/spherical.cpp
    - examples/events/single-event.dat
  requires:
    - {{ compiler('cxx') }}
  commands:
    - test -f $PREFIX/lib/libsiscone${SHLIB_EXT}
    - test -f $PREFIX/lib/libsiscone_spherical${SHLIB_EXT}
    - test -f $PREFIX/include/siscone/config.h
    - test -f $PREFIX/include/siscone/geom_2d.h
    - test -f $PREFIX/include/siscone/defines.h
    - test -f $PREFIX/include/siscone/circulator.h
    - test -f $PREFIX/include/siscone/area.h
    - test -f $PREFIX/include/siscone/ranlux.h
    - test -f $PREFIX/include/siscone/quadtree.h
    - test -f $PREFIX/include/siscone/protocones.h
    - test -f $PREFIX/include/siscone/momentum.h
    - test -f $PREFIX/include/siscone/hash.h
    - test -f $PREFIX/include/siscone/vicinity.h
    - test -f $PREFIX/include/siscone/split_merge.h
    - test -f $PREFIX/include/siscone/siscone.h
    - test -f $PREFIX/include/siscone/siscone_error.h
    - test -f $PREFIX/include/siscone/reference.h
    - test -f $PREFIX/include/siscone/spherical/geom_2d.h
    - test -f $PREFIX/include/siscone/spherical/vicinity.h
    - test -f $PREFIX/include/siscone/spherical/split_merge.h
    - test -f $PREFIX/include/siscone/spherical/siscone.h
    - test -f $PREFIX/include/siscone/spherical/protocones.h
    - test -f $PREFIX/include/siscone/spherical/momentum.h
    - test -f $PREFIX/include/siscone/spherical/hash.h

    - cd examples/
    - $CXX main.cpp options.cpp -o main $CXXFLAGS $LDFLAGS -lsiscone
    - ./main
    - $CXX area.cpp options.cpp -o area $CXXFLAGS $LDFLAGS -lsiscone
    - ./area
    - $CXX sample.cpp -o sample $CXXFLAGS $LDFLAGS -lsiscone
    - ./sample
    - $CXX test.cpp -o test $CXXFLAGS $LDFLAGS -lsiscone
    - ./test
    - $CXX times.cpp -o times $CXXFLAGS $LDFLAGS -lsiscone
    - ./times  # [build_platform == target_platform]
    - $CXX spherical.cpp -o spherical $CXXFLAGS $LDFLAGS -lsiscone -lsiscone_spherical
    - ./spherical

about:
  home: https://gitlab.com/fastjet/siscone
  summary: 'SISCone: the Seedless Infrared Safe Cone Jet Algorithm'
  description: |
    SISCone was written by Gavin Salam and Gregory Soyez.

    A description of the algorithm is available in the publication
    JHEP 05 (2007) 086
    [[arXiv:0704.0292](https://arxiv.org/abs/0704.0292) (hep-ph)].
    DOI: [10.1088/1126-6708/2007/05/086](https://doi.org/10.1088/1126-6708/2007/05/086)
  license: AGPL-1.0-only
  license_family: AGPL
  license_file: COPYING
  dev_url: https://gitlab.com/fastjet/siscone

extra:
  recipe-maintainers:
    - kratsg
    - matthewfeickert
