context:
  name: "siscone"
  version: "3.1.3"

recipe:
  name: ${{ name }}-split
  version: ${{ version }}

source:
  url: https://gitlab.com/fastjet/siscone/-/archive/siscone-${{ version }}/siscone-siscone-${{ version }}.tar.gz
  sha256: 682626a678df152d5d6cf915f54cd2879efe77898544ef23c0b83626899c31e5
  patches:
    - 0001-use-imported-getopt.patch

build:
  number: 1

outputs:
  - package:
      name: ${{ name }}

    build:
      files:
        - if: unix
          then:
            - lib/libsiscone*.so*
            - lib/libsiscone*.dylib
        - if: win
          then:
            - Library/bin/siscone*.dll
      script:
        - if: win
          then: cmake %CMAKE_ARGS% -DSISCONE_ENABLE_DEBUG=OFF -S . -B build
          else: cmake ${CMAKE_ARGS} -DSISCONE_BUILD_EXAMPLES=OFF -DSISCONE_ENABLE_DEBUG=OFF -DCMAKE_INSTALL_PREFIX="${PREFIX}" -S . -B build
        - cmake -LH build
        - if: win
          then: cmake --build build --config=Release --parallel="%CPU_COUNT%"
          else: cmake --build build --parallel="${CPU_COUNT}"
        - cmake --install build

    requirements:
      run_exports:
        - ${{ pin_subpackage('siscone', upper_bound='x.x') }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - if: unix
          then: make
        - if: win and build_platform != target_platform
          then: getopt-win32
      host:
        # only the win examples link getopt; the libraries do not
        - if: win
          then: getopt-win32
      ignore_run_exports:
        from_package:
          - if: win
            then: getopt-win32

    tests:
      - package_contents:
          lib:
            - if: unix
              then:
                - siscone
                - siscone_spherical
          bin:
            - if: win
              then:
                - siscone.dll
                - siscone_spherical.dll
          files:
            not_exists:
              - include/**
              - lib/cmake/**
              - Library/include/**
              - Library/lib/**

  - package:
      name: ${{ name }}-devel

    build:
      files:
        - if: unix
          then:
            - include/siscone/**
            - lib/cmake/siscone/**
        - if: win
          then:
            - Library/include/siscone/**
            - Library/lib/cmake/siscone/**
            - Library/lib/siscone*.lib
      script:
        - if: win
          then: cmake %CMAKE_ARGS% -DSISCONE_ENABLE_DEBUG=OFF -S . -B build
          else: cmake ${CMAKE_ARGS} -DSISCONE_BUILD_EXAMPLES=OFF -DSISCONE_ENABLE_DEBUG=OFF -DCMAKE_INSTALL_PREFIX="${PREFIX}" -S . -B build
        - cmake -LH build
        - if: win
          then: cmake --build build --config=Release --parallel="%CPU_COUNT%"
          else: cmake --build build --parallel="${CPU_COUNT}"
        - cmake --install build

    requirements:
      run_exports:
        - ${{ pin_subpackage('siscone', upper_bound='x.x') }}
      build:
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
        - cmake
        - if: unix
          then: make
        - if: win and build_platform != target_platform
          then: getopt-win32
      host:
        - if: win
          then: getopt-win32
      ignore_run_exports:
        from_package:
          - if: win
            then: getopt-win32
      run:
        - ${{ pin_subpackage('siscone', exact=True) }}

    tests:
      - package_contents:
          files:
            exists:
              - etc/conda/test-files/siscone-devel/0/examples/events/single-event.dat
              - if: unix
                then:
                  - lib/cmake/siscone/siscone*.cmake
                  - etc/conda/test-files/siscone-devel/0/examples/*.cpp
              - if: win
                then:
                  - Library/lib/cmake/siscone/siscone*.cmake
                  - etc/conda/test-files/siscone-devel/0/build/examples/Release/*.exe
            not_exists:
              - lib/*.so*
              - lib/*.dylib
              - Library/bin/*.dll
          include:
            - siscone/config.h
            - siscone/geom_2d.h
            - siscone/defines.h
            - siscone/circulator.h
            - siscone/area.h
            - siscone/ranlux.h
            - siscone/quadtree.h
            - siscone/protocones.h
            - siscone/momentum.h
            - siscone/hash.h
            - siscone/vicinity.h
            - siscone/split_merge.h
            - siscone/siscone.h
            - siscone/siscone_error.h
            - siscone/reference.h
            - siscone/spherical/geom_2d.h
            - siscone/spherical/vicinity.h
            - siscone/spherical/split_merge.h
            - siscone/spherical/siscone.h
            - siscone/spherical/protocones.h
            - siscone/spherical/momentum.h
            - siscone/spherical/hash.h
          lib:
            - if: win
              then:
                - siscone.lib
                - siscone_spherical.lib
      - script:
          - if: unix
            then:
              - cd examples/
              - $CXX main.cpp options.cpp -o main $CXXFLAGS $LDFLAGS -lsiscone
              - ./main
              - $CXX area.cpp options.cpp -o area $CXXFLAGS $LDFLAGS -lsiscone
              - ./area
              - $CXX sample.cpp -o sample $CXXFLAGS $LDFLAGS -lsiscone
              - ./sample
              - $CXX test.cpp -o test $CXXFLAGS $LDFLAGS -lsiscone
              - ./test
              - $CXX times.cpp -o times $CXXFLAGS $LDFLAGS -lsiscone
              - if: build_platform == target_platform
                then: ./times
              - $CXX spherical.cpp -o spherical $CXXFLAGS $LDFLAGS -lsiscone -lsiscone_spherical
              - ./spherical
          - if: win
            then:
              - cd examples
              - ..\build\examples\Release\siscone_main.exe
              - ..\build\examples\Release\siscone_area.exe
              - ..\build\examples\Release\sample.exe
              - ..\build\examples\Release\siscone_test.exe
              - if: build_platform == target_platform
                then: ..\build\examples\Release\times.exe
              - ..\build\examples\Release\spherical.exe
        files:
          source:
            - if: win
              then:
                - build/examples/Release/siscone_main.exe
                - build/examples/Release/siscone_area.exe
                - build/examples/Release/sample.exe
                - build/examples/Release/siscone_test.exe
                - build/examples/Release/times.exe
                - build/examples/Release/spherical.exe
            - if: unix
              then:
                - examples/main.cpp
                - examples/options.cpp
                - examples/options.h
                - examples/area.cpp
                - examples/sample.cpp
                - examples/test.cpp
                - examples/times.cpp
                - examples/spherical.cpp
            - examples/events/single-event.dat
        requirements:
          run:
            - if: win
              then: getopt-win32
            - if: unix
              then: ${{ compiler('cxx') }}

about:
  homepage: https://gitlab.com/fastjet/siscone
  summary: 'SISCone: the Seedless Infrared Safe Cone Jet Algorithm'
  description: |
    SISCone was written by Gavin Salam and Gregory Soyez.

    A description of the algorithm is available in the publication
    JHEP 05 (2007) 086
    [[arXiv:0704.0292](https://arxiv.org/abs/0704.0292) (hep-ph)].
    DOI: [10.1088/1126-6708/2007/05/086](https://doi.org/10.1088/1126-6708/2007/05/086)
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  repository: https://gitlab.com/fastjet/siscone

extra:
  feedstock-name: siscone
  recipe-maintainers:
    - lgray
    - kratsg
    - matthewfeickert
